apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-yvlr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-yvlr
    app.kubernetes.io/part-of: cin4s-839-0014-app
  name: devfile-sample-yvlr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-yvlr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-yvlr
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0014-tenant/cin4s-839-0014-app/devfile-sample-yvlr@sha256:00ffd85dbbc7646451e339b9930327814c3bc849b4b8669bae8a104f5a3c6fc8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
